"""phonen umber for lead

Revision ID: 95e1ef45dcb6
Revises: 89fb47f5d975
Create Date: 2023-06-30 14:24:06.349457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e1ef45dcb6'
down_revision = '89fb47f5d975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_column('clients', 'phone_number')
    # ### end Alembic commands ###
